name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

    - name: Run tests in Docker container
      uses: docker://ghcr.io/${{ github.repository_owner }}/diffs_project:${{ steps.get_version.outputs.VERSION }}
      with:
        args: pytest tests/

#name: Python Tests
#
#on: [push]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: '3.12'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#    - name: Test with pytest
#      run: |
#        pytest tests/
