name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHR_HASH }}

    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

    - name: Get Repo Name
      id: get_repo_name
      run: echo "REPO_NAME=$(echo "${{ github.repository }}" | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

    - name: Debug
      id: debug
      run: |
        echo "Got this far!!!! ${{ steps.get_version.outputs.VERSION }} ${{ steps.get_repo_name.outputs.REPO_NAME }}"
        echo "Repository: ${{ github.repository }}"
        echo "Version: ${{ steps.get_version.outputs.VERSION }}"
        echo "Full image name: ghcr.io/${{ steps.get_repo_name.outputs.REPO_NAME }}:${{ steps.get_version.outputs.VERSION }}"

    - name: Pull Docker container
      run: |
        docker pull --platform linux/amd64 ghcr.io/${{ steps.get_repo_name.outputs.REPO_NAME }}:${{ steps.get_version.outputs.VERSION }}

    - name: Run tests in Docker container
      run: |
        docker run --rm --platform linux/amd64 ghcr.io/${{ steps.get_repo_name.outputs.REPO_NAME }}:${{ steps.get_version.outputs.VERSION }} pytest tests/